### PR TITLE
Updates to the wofs docs for the new wofs_ls products

### PR DESCRIPTION
**Pull request by eloise-b**
WOfS Documentation update:
- includes caveats
- name and path changes for the products
- updates to reflect the new product

### CODE REVIEW

**Comment by eefaye** [comment]
I've made a few minor changes. Looks good to me. @fangfy  we don't currently have any "examples of where WOfS works well" as mentioned in the correspondence chain. Do we want to add those or merge first?

**Comment by fangfy** [comment]
> I've made a few minor changes. Looks good to me. @fangfy we don't currently have any "examples of where WOfS works well" as mentioned in the correspondence chain. Do we want to add those or merge first?

Yes, I think we want to add some example images before we merge and release.

**Comment by fangfy** [comment]
@eefaye updated the text a bit more especially the data types and removal of reference to percentage while we actually provide frequency.

**Comment by eefaye** [comment]
@fangfy Ready for final review

**Review by fangfy — APPROVED** [review]
Looks good to me.

**Pull request merged**
