### PR TITLE
adding the wofs docs

### PR DESCRIPTION
**Pull request by eloise-b**

### CODE REVIEW

**Comment by andrewdhicks** [comment]
It is looking really good Eloise!
I think the only thing I would suggest is to remove "Technical specifications" from the main heading.

@eefaye, if there are particular sandbox notebooks that demonstrate a product, should we link to them from the product page, or only the other way round?

**Comment by fangfy** [comment]
Few comments:
* I'd remove mention of confidence layer and filter product because we probably won't do it.
* I'd switch the order to go from feature layer, to annual to all time summary. More intuitive? 
* Have a measurements table (list bands) for each of the wofl, annual and all time summary products with data type etc 
* The bit flag only applies for wofl. Would probably also make the description shorter.
* Should the validation be under methods? should it be its own section? not sure
* Get Meghan to check the validation and technical information section

**Comment by eefaye** [comment]
@andrewdhicks  in reply to your question, I think it should go both ways. Perhaps that's something we can change across all the technical specs pages once the URL is finalised?

**Comment by eefaye** [comment]
@fangfy  Edits made as suggested:

 - Changed disclaimer
 - Removed broken link to the WOFL technical specs
 - Expanded acronym in table caption
 - Added "Algorithm" to Technical Information
 - Added AWS info

**Review by fangfy — APPROVED** [review]

**Pull request merged**
