### PR TITLE
Geomad specs

### PR DESCRIPTION
**Pull request by eefaye**
Added data_specs folder and _static/data_specs folder.
Added GeoMAD technical specifications document.

### CODE REVIEW

**Comment by eefaye** [comment]
@andrewdhicks  I'm not sure I did the `index` pages correctly, a review would be much appreciated. Also I think the ipynb checkpoints folder is perhaps not supposed to be there...

**Comment by eefaye** [comment]
@andrewdhicks 
* **Technical specs** removed from title. I suppose I want to distinguish it from any other page called "GeoMAD" (also debating taking the "annual" out) but I guess it will be under the **Data specs** subheading or equivalent
* It seems almost ALL the equations go off the page. I will try realigning and scaling them smaller; the very long ones are probably a lost cause and might need to be removed... inconvenient we can't split fractions over multiple lines.  @fangfy  
* Table A.1 headings have been shortened.

Fang, the readthedocs site preview is blocked by the GA proxy on Chrome, but not on Firefox if you have proxies turned off.

**Comment by fangfy** [comment]
Suggest some rearrangement to make the sectioning more applicable to other datasets.
* Can the Technical Explanation be the "Technical Information" section in CMI?
* Add a Data Access section after product overview, subsection of ODC (odc product name and aliases would go here), S3 (bucket, path and filename), OWS (ows layer)
* Specification in product overview needs to be not ODC focused: table 1, expand product name to Annual Sentinel-2 GeoMAD, remove ODC product name; table 2, replace aliases column with short description; move ODC related text to Data Access-> ODC.
* Not sure processing steps are useful. Suggest combine major algorithm, source and processing steps into one section, processing, lineage or algorithm?
* Add license and acknowledgement in the reference section (see CMI)

**Comment by eefaye** [comment]
Thanks Fang! 
- [x] Can the Technical Explanation be the "Technical Information" section in CMI? **Done**

- [x] Add a Data Access section after product overview, subsection of ODC (odc product name and aliases would go here), S3 (bucket, path and filename), OWS (ows layer) **Section added. Not sure of the S3/OWS details.**

 - [x] Specification in product overview needs to be not ODC focused: table 1, expand product name to Annual Sentinel-2 GeoMAD, remove ODC product name; table 2, replace aliases column with short description; move ODC related text to Data Access-> ODC. **Done, I tried to keep generic info in Overview and moved ODC-specifics to Data Access, please check**

 - [x] Not sure processing steps are useful. Suggest combine major algorithm, source and processing steps into one section, processing, lineage or algorithm? **Steps removed, subsection now titled "Processing lineage and algorithm", but there's not much content there for GeoMAD. It would be nice to have more details there?**

In progress:

 - [ ] Add license and acknowledgement in the reference section (see CMI) 
 - [ ] Optimising equations for webpage

**Pull request merged**
