### PR TITLE
Soil docs

### PR DESCRIPTION
**Pull request by mickwelli**
Add soil docs pages. There are 6 products with 2-4 measurements each, so I've added a docs page for each product.

### CODE REVIEW

**Review by mpho-sadiki — COMMENTED** [review]
Hi Michael. Please see a few changes or suggestions below:

For all docs, under Specifications"
- Consider adding reference to the iSDAsoil Jupyter notebook. - "A Jupyter Notebook which demonstrates loading and using iSDA soil products in the Sandbox is also available"
- Perhaps consider bringing the text that refers to the DE Africa Metadata Explorer together (and have it be under table 1) like this: '_Relevant metadata for the iSDA soil bedrock depth product, as well as the specific temporal and geographic extents for the product, can be explored through the DE Africa Metadata Explorer. Data is available for the shaded region as shown in Figure 1._’
- The "Data Acess" heading contains a typo. It should be "Data Access".
- Is a list of **Related Services** necessary? Like listing the other iSDASoil products?

There is an issue with how the units are showing for Figure 2: iSDA soil bulk density **(g/cm:math:`^3`)** for an area near Cape Town, South Africa.
- The same Figure captions for some the other products do not include the units. E.g., _Figure 2: iSDA soil bedrock depth _(insert units)_ for an area near Cape Town, South Africa._

**Comment by mickwelli** [comment]
Thank you @mpho-sadiki, very helpful. I've taken the following actions:

- Added link to Jupyter notebook
- Group the text referring to the Metadata explorer
- Corrected the 'Data Access' typos
- Added a Related Datasets subsection which refers to the other soils products
- Corrected the units for soil bulk density and added units to the captions for other plots

**Comment by mickwelli** [comment]
Thanks for the suggestions @mpho-sadiki. I've tidied up the single soils doc and deleted the individual pages. It would be great to have another set of eyes over it.

**Comment by mpho-sadiki** [comment]
> Thanks for the suggestions @mpho-sadiki. I've tidied up the single soils doc and deleted the individual pages. It would be great to have another set of eyes over it.

Looks good Michael. Just one minor change in the in the iSDA variables description where it says  20-5cm depth instead of  20-50cm depth. I also think that "_We will see through the notebook that we can bring in each variable with the Access Names e.g. ‘bedrock_depth’._" should be removed or the link to the notebook added.

**Comment by mickwelli** [comment]
Thanks, those edits have been made

**Review by mpho-sadiki — APPROVED** [review]
Looks good, Michael.

**Review by nanaboamah89 — APPROVED** [review]

**Review by lisarebelo — APPROVED** [review]

**Pull request merged**
